name: Build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
  push:
    branches:
      - main
      - ci
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.77.2
          components: clippy, rustfmt
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.pgrx/
            ~/.cache/pip/
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo fmt --check
      - run: cargo install --locked cargo-pgrx 
      - run: cargo pgrx init --pg16 download
      - run: cargo clippy
      - run: make test
      - run: make build
