name: Build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
  push:
    branches:
      - main
      - ci
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.77.2
          components: clippy, rustfmt
      - uses: actions/setup-python@v5
      - uses: actions/cache@v4
        with:
          path: |
            ~/.pgrx
            ~/.cargo
          key: ${{ runner.os }}-deps
      - run: cargo fmt --check
      - run: cargo install --locked cargo-pgrx 
      - run: cargo clippy
      - run: cargo pgrx init --pg16 download
      - run: make test
      - run: make build
