name: Build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
  push:
    branches:
      - main
      - ci
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
    
env:
  RUST_TOOLCHAIN_VERSION: 1.77.2

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          components: clippy, rustfmt
      - run: cargo fmt --check
      - run: cargo clippy
  
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pgrx
            ~/.cargo
          key: ${{ runner.os }}-deps
      - run: make init

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
      - name: Cache pgrx
        uses: actions/cache@v4
        with:
          path: /home/runner/.pgrx
          key: ${{ runner.os }}-pgrx
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pgrx
            ~/.cargo
          key: ${{ runner.os }}-deps
      - run: make test
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pgrx
            ~/.cargo
          key: ${{ runner.os }}-deps
      - run: make build
