name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md

  push:
    branches:
      - main
      - ci
    paths-ignore:
      - README.md
      - CONTRIBUTING.md

  release:
    types:
      - created

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.77.2
          components: clippy, rustfmt
      - uses: actions/cache@v4
        with:
          path: ~/.pgrx/
          key: ${{ runner.os }}-pgrx-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip/
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Makefile') }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: make init
      - run: make lint
      - run: make test
